name: 'GSA/grace-example'
description: 'Example implementation of the GSA Readily Available Computing Environment (GRACE) platform'
license: null
openSourceProject: 1
governmentWideReuseProject: 1
tags:
    - open-source
    - opensource
    - grace
    - devsecops
contact:
    email: devsecops-core@gsa.gov
