version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Install openssl make sudo and unzip
          command: apk add --update openssl make sudo unzip
      - run:
          name: Install Packer
          command: |
            pwd
            ls -l
            wget https://releases.hashicorp.com/packer/1.2.5/packer_1.2.5_linux_amd64.zip
            ls -l
            unzip -f packer_1.2.5_linux_amd64.zip
            ls -l
            sudo mv packer /usr/local/bin/packer
          working_directory: /tmp
      - run:
          name: Decrypt environment variables
          command: openssl aes-256-cbc -d -in secret-env-cipher -out secret-env-plain -k $KEY
          working_directory: ~/project/terraform/bootstrap
      - run:
          name: Decrypt network tfvars
          command: openssl aes-256-cbc -d -in secret-tfvars-cipher -out terraform.tfvars -k $KEY
          working_directory: ~/project/terraform/networking
      - run:
          name: Validate terraform
          command: |
            source terraform/bootstrap/secret-env-plain
            make validate
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  deploy_example:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install make sudo and unzip
          command: apk add --update make sudo unzip
      - run:
          name: Install Packer
          command: |
            wget https://releases.hashicorp.com/packer/1.2.5/packer_1.2.5_linux_amd64.zip
            unzip -f packer_1.2.5_linux_amd64.zip
            sudo mv packer /usr/local/bin/packer
          working_directory: /tmp
      - run:
          name: Deploy the full example
          command: |
            source terraform/bootstrap/secret-env-plain
            make deploy

workflows:
  version: 2

  validate_and_deploy:
    jobs:
      - validate
      - deploy_example:
          filters:
            branches:
              only: master
          requires:
            - validate
